-- indicate a Runtime node: it should not exist in the AST generated by the parser but only as a result of an evaluation or call
-- is assumed to be already evaluated and prepared (will actually error on prepare)

local ast = require("anselme.ast")

return ast.abstract.Node {
	type = "runtime",
	init = false,

	_evaluated = true,
	_prepared = true
}
